
REVOKE EXECUTE ON FUNCTION public.nearby_minyanim(DOUBLE PRECISION, DOUBLE PRECISION, INTEGER) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.nearby_minyanim(DOUBLE PRECISION, DOUBLE PRECISION, INTEGER) TO authenticated;
